#+TITLE: compact org-mode guide
#+setupfile:theme-readtheorg.setup
#+OPTIONS:   toc:3 
#+AUTHOR:    Hoyoul Park

* Introduction

** Preface
Org는 mode다. 용도는 메모를 기록하거나, 해야할 일(Todo)를 쓰거나, Project를 계획하는 데 사용한다.
Plain Text로 작성된다. source code도 embede할 수 있다.

** Installation
Emacs 24이상에선 built-in되어 있어서 별도로 설치가 필요 없다.
** Activation
아래는 자주 사용되는 기능이라서 global key롤 설정한다. .emacs.d/init.el에 기록하면 된다.
#+BEGIN_SRC comment
   ;; The following lines are always needed.  Choose your own keys.
      (global-set-key "\C-cl" 'org-store-link)
      (global-set-key "\C-ca" 'org-agenda)
      (global-set-key "\C-cc" 'org-capture)
      (global-set-key "\C-cb" 'org-switchb)
#+END_SRC
** Feedback
연락처는 emacs-orgmode@gnu.org라고 한다.
* Document Structure
#+begin_note
org는 outline mode에 기반을 두고 여러 명령어와 구조를 추가시켜 만든 mode다.
#+end_note
** outlines
#+begin_note
<TAB>이 org-cycle이고, 이기능은 특정 영역을 show/hide 할 수 있다.
#+end_note

org는 outline모드를 기반으로 한다고 했다. outline은 문서를
hiearchical한 구조로 만든다. 그러한 format을 가지고 있다는 말이다.
Hiearchical구조라는 것은 부모/자식간의 관계가 있다는 것인데, 이런
구조가 메모나 생각들을 정리하기엔 저자는 최고의 문서 구조라고
생각한다. 아주 긴 내용의 문서의 경우 현재 작업중인 부분만 보여주고,
나머지는 구조만 보여줄 수 가 있기 때문에 이런 구조가 매우 적합한
것이다.  이렇게 show/folding을 할수 있는 기능을 org에선 단 한개의
명령만을 사용한다. 그렇다면 outline mode에서는 여러개의 명령어가
있다는 것인가? org모드에서는 org-cycle이란 명령어가 show/hide기능을
한다. 이 명령어는 <TAB>에 바운드 되어 있다.

** headlines

** visibility cycling

** motion

** Structure editing

** sparse trees

** plain lists

** footnotes


* Tables

* Hyperlinks

* TODO Items

* Tags

* Properties

* Dates and Times

* Capture-Refile-Archive

* Agenda Views

* Markup for rich export

* Exporting

* Publishing

* Working with source code

* Miscellaneous
